/* GENERATED by tools/build_version.py from version.json + CHANGELOG.md. Do not edit. */
window.WS_BUILD = {
 "versionName": "0.1.2",
 "versionCode": 3,
 "releasedAt": "2026-09-27",
 "notes": [
  "**Book a job is the customer's form.** The office now books a call on exactly the same form the customers use — same boxes, same order, same look, with Pin my location and Pick on map too. Change the customer's form and Book a job and Edit change with it.",
  "**Nothing is missed in silence.** Press Book it or Send the booking with something missing and every box that needs it turns red and shakes, with a line under it saying what to fill in. Typing in a red box takes the red away.",
  "**The top bar runs the full width** of the screen, so the photo no longer shows beside it."
 ],
 "updateUrl": "https://github.com/Winter-Air-Services/winter-air-services.github.io/releases/latest/download/update.json"
};
