/* GENERATED by tools/build_version.py from version.json + CHANGELOG.md. Do not edit. */
window.WS_BUILD = {
 "versionName": "0.2.0",
 "versionCode": 18,
 "releasedAt": "2026-09-28",
 "notes": [
  "**🖼️ Photos on the booking page — yours.** Admin → Page photos: add up to six. Each one is cropped first (drag it, zoom it; the dashed box is what phones show), and the page fades from one to the next on its own. Remove takes one off for good.",
  "**📤 Send as PDF.** On the quotation, under Print: the quotation goes straight to Messenger, Viber, email, Bluetooth or Drive as a PDF file — no more Print → Save → Files.",
  "**Not paid, from the start.** Every open job — not scheduled, scheduled, in progress or done — shows **Not paid** in red until you mark it paid. GCash blue and Paid green as before.",
  "**A customer's bookings open.** Customers → a customer → Bookings: tap one for the booking itself, its Full status and its quotation — the same as in the Inbox.",
  "**The shop's logo** at the top left of the app.",
  "**A new app icon:** the shop's WA logo, on white — no more white strips around it."
 ],
 "updateUrl": "https://github.com/Winter-Air-Services/winter-air-services.github.io/releases/latest/download/update.json"
};
