/* GENERATED by tools/build_version.py from version.json + CHANGELOG.md. Do not edit. */
window.WS_BUILD = {
 "versionName": "0.1.1",
 "versionCode": 2,
 "releasedAt": "2026-09-27",
 "notes": [
  "**A new look for the booking page.** A photo across the top, the form in a card laid over it, and a **Rather talk?** button that rings the shop. The photo is a stand-in until we have one of the shop or the van.",
  "**Track my booking sits beside the form** on a computer, under the photo, instead of far down the page."
 ],
 "updateUrl": "https://github.com/Winter-Air-Services/winter-air-services.github.io/releases/latest/download/update.json"
};
